### ISSUE TITLE
Usage of python wrapper

### ISSUE THREAD

**Issue by gpapadop79** [lvdmaaten/bhtsne#15]
Hello!

I compiled the program and tried the matlab example and it works.

But when I try the python wrapper, no bh_tsne.exe process is starting and I get nothing in the output, so I don't know what is the problem. My system is windows 7 x64.

Could you please provide a similar usage example for python like the one for matlab?

Thanks in advance

**Comment by lvdmaaten** [comment]
Can you provide a code sample that allows me to reproduce your issue?

**Comment by gpapadop79** [comment]
Sorry for the delayed answer.
Actually when I run the wrapper with arguments (which is how it is designed), it works fine.
`python bhtsne.py -i Xtrain.csv -o Xtsne.csv`

The problem I mentioned occurs when I try to call bhtsne.py within another python script, because I want to pass the data to visualize as a numpy array, like you can do with the matlab wrapper.

So I tried:
`import bhtsne`
`bhtsne.bh_tsne(Xtrain)`

and also
`bhtsne.bh_tsne(Xtrain_svd, no_dims=2, initial_dims=50, perplexity=30, theta=0.5, randseed=-1, verbose=True)`

but no bh_tsne.exe process is starting and the output is something like:
`<generator object bh_tsne at 0x0000000008F45900>`

I suppose the bhtsne.py script needs modifications to work, is there any quick hack we can do?

Thanks

I'm using anaconda python 2.5 on windows 7 x64

**Comment by ajdroid** [comment]
Look at the `main()` in `bhtsne.py`

**Comment by gpapadop79** [comment]
ok after some testing I figured out that the problem really was that I didn't know what is a generator function in python, because the main function bh_tsne is actually a generator.

So I just had to convert the output to a numpy array.
I finally added a function run_tsne for calling bh_tsne from another script which justs passes the parameters and returns a numpy array

```
def run_tsne(data, no_dims=DEFAULT_NO_DIMS, perplexity=DEFAULT_PERPLEXITY, theta=DEFAULT_THETA, randseed=EMPTY_SEED, verbose=True, initial_dims=INITIAL_DIMENSIONS):

   result = bh_tsne(data, no_dims=no_dims, perplexity=perplexity, theta=theta, randseed=randseed, verbose=verbose, initial_dims=initial_dims)
   return np.asarray(list(result))
```

so now this works fine:
```
import bhtsne
bhtsne.run_tsne(Xtrain)
```

**Comment by RobRomijnders** [comment]
Can you help me a little? Why does this not work? I added the run_tsne() function to the bhtsne.py

```python
import sys
import numpy as np
sys.path.append('/home/rob/Dropbox/ml_projects/tSNE/bhtsne-master')
import bhtsne


X_train = np.loadtxt('/home/rob/Dropbox/ml_projects/FCN/X_train.csv', delimiter=',')
y_train = np.loadtxt('/home/rob/Dropbox/ml_projects/FCN/y_train.csv', delimiter=',')

result = bhtsne.run_tsne(X_train)
```

**Comment by lvdmaaten** [comment]
I'm afraid I cannot be of much help here: I don't actually speak Python... :)

**Comment by gpapadop79** [comment]
@RobRomijnders first thing to check is whether the wrapper is launching a bh_tsne.exe process. 
I suspect that in your case it doesn't and the code takes a while to run because the wrapper applies PCA to the data as a preprocessing step before TSNE.

Anyway if that is the case, first thing I would check is the path to the executable. 
It is defined in line 54 of bhtsne.py. If you are running this on windows the executable must be in a folder named "windows"
