### ISSUE TITLE
 pre_Installation of toolboxes in Matlab R2015b

### ISSUE THREAD

**Issue by linyi777** [lvdmaaten/bhtsne#17]
Hello~

Thank you very much to share.

I want to use your code on Matlab R2015b, Do I need to pre-install any software or toolbox?

**Comment by stephenholtz** [comment]
It relies on the matlab statistics toolbox pca function, so you could check that you have this (run `edit pca`). You should also check that you are able to complete the steps under the installation section of the README file. I did this and have had success on OSX and Linux.
