### ISSUE TITLE
Segmentation Fault: 11 on NaN data

### ISSUE THREAD

**Issue by kylemcdonald** [lvdmaaten/bhtsne#2]
First, thanks a ton for this research and the implementation! [Here's](https://vimeo.com/135511186) one thing and [another](https://www.flickr.com/photos/kylemcdonald/18877593190) I've been using it for.

So, it's totally my fault that I fed NaNs to bh_tsne but the crash was a little mysterious, so I thought I would post an issue in case someone else ran into the same thing. From the Python wrapper I see:

```sh
 - point 0 of 30583
Traceback (most recent call last):
  File "bh_tsne/bhtsne.py", line 176, in <module>
    exit(main(argv))
  File "bh_tsne/bhtsne.py", line 167, in main
    verbose=argp.verbose):
  File "bh_tsne/bhtsne.py", line 125, in bh_tsne
    'refer to the bh_tsne output for further details')
AssertionError: ERROR: Call to bh_tsne exited with a non-zero return code exit status, please refer to the bh_tsne output for further details
```

Then, copying the `data.dat` and feeding it to the binary with a debugger, I see it crashes here with `EXC_BAD_ACCESS` (or `Segmentation Fault: 11` when you run it without a debugger):

```c++
            // Compute Gaussian kernel row
            for(int m = 0; m < K; m++) cur_P[m] = exp(-beta * distances[m + 1]);
```

`distances` is 0-length, so I look at my data closer, sorting it and looking for duplicate or weird rows. I noticed some NaNs and verified it with this at the end of `TSNE::load_data` 

```c++
    int k = 0;
    for(int i = 0; i < *n; i++) {
        for(int j = 0; j < *d; j++) {
            if(isnan((*data)[k++])) {
                printf("Found NaN at %i x %i!\n", i, j);
            }
        }
    }
```

A quick hack to clean the data `grep -v 'nan' vectors > vectors-clean` and it looks like it's working, but now I need to fix the original cause of the problem :)

**Comment by lvdmaaten** [comment]
Thanks for sharing! `distance` is a `vector` so it may have an initial size of `0`. So I do not really understand why you would get a segfault in that particular line: `cur_P` should also have the right size unless the number of neighbors `K` or the number of data points `N` was erroneously read from the data file (the communication via files between wrapper and C++ code is admittedly a bit flaky), but I do not really understand why that would happen here: the `NaN`s should be after `N` and `K` in the data file. But I'm probably missing something here... :)

Anyway: the easiest work-around would be to do a `NaN` check either in the C++ code or in the wrapper before running any actual code. If you have time, feel free to send a pull request fixing that! :)
