### ISSUE TITLE
indexing bugs in tsne.cpp

### ISSUE THREAD

**Issue by airvine2** [lvdmaaten/bhtsne#28]
Hello, 
I have found some indexing bugs in the methods
 TSNE::computeSquaredEuclideanDistance
and
TSNE::run
for the Exact computation of tSNE.  (in the section where you symmetrize the input probability matrix)
If this has already been corrected, thank you, and please let me know and I will make sure I obtain the updated version. 

In both cases, 2 nested loops are being used with a similar indexing format. I will use the euclidean distance matrix calculation to describe what I see:

nN = 0; nD = 0;
for(int n = 0; n < N; n++) {
      int mD = 0;                                                //always indexes to the first data point in X
      DD[nN + n] = 0.0;
      for(int m = n + 1; m < N; m++) {              
             DD[nN + m] = 0.0;
             for(int d = 0; d < D; d++) {
                DD[nN + m] += (X[nD + d] - X[mD + d]) * (X[nD + d] - X[mD + d]);
            }
            DD[m * N + n] = DD[nN + m];
            mD+=D;
      }
     nN+=N;
    nD += D;
}

The problem is that mD always starts at 0, but m always starts at n+1. It seems that what is intended is that mD should contain the index of the m'th data point in X. If we describe DD as a matrix instead of an array, when you process row 0, you end up calculating the following:
DD[0,1] = ||x0 - x0||^2
DD[0,2] = ||x0 - x1||^2
DD[0,3] = ||x0 - x2||^2
where x0 is the first point, x1 is the second point, and x2 is the third point. In processing the second row, you get:
DD[1,2] = ||x1 - x0||^2
DD[1,3] = ||x1 - x1||^2
DD[1,4] = ||x1 - x2|| ^2

This can be fixed by changing the value of mD:

int mD;
nN = 0; nD = 0;
for(int n = 0; n < N; n++) {
      // int mD = 0;                                    //remove this line
      DD[nN + n] = 0.0;
      for(int m = n + 1; m < N; m++) {     
             mD = m * D;                               //this is the added code         
             DD[nN + m] = 0.0;
             for(int d = 0; d < D; d++) {
                DD[nN + m] += (X[nD + d] - X[mD + d]) * (X[nD + d] - X[mD + d]);
            }
            DD[m * N + n] = DD[nN + m];
           // mD+=D;                                      //remove this line
      }
     nN+=N;
    nD += D;
}

The bug fix in TSNE::run is similar:

// Symmetrize input similarities
printf("Symmetrizing...\n");
int nN = 0;
for(int n = 0; n < N; n++) {
     //int mN = 0;                                            //remove this line
     for(int m = n + 1; m < N; m++) {
		int mN = m*N;                                //this is the added code
                P[nN + m] += P[mN + n];
                P[mN + n]  = P[nN + m];
                //mN += N;                                  //remove this line
     }
     nN += N;
}
  
As a last note, thank you for providing this technique and implementation. It has proved to be a great embedding technique for the type of data I work with.   

Sincerely,

Allison

**Comment by lvdmaaten** [comment]
In `computeSquaredEuclideanDistance()`, wasn't this issue resolved by https://github.com/lvdmaaten/bhtsne/commit/5f00c7dcdeb0a9faef682ab3f85cb8a2bbc8419b?

The symmetrization, indeed, appears to have a bug. Will send out a fix shortly!

**Comment by lvdmaaten** [comment]
Resolved by https://github.com/lvdmaaten/bhtsne/commit/002cddf3cab6e9896902230a8e7006cdd2800abd

Thanks for spotting this!
