### ISSUE TITLE
run_bh_tsne expects an input file not a numpy array

### ISSUE THREAD

**Issue by HansPinckaers** [lvdmaaten/bhtsne#31]
After #29 my code doesn't run anymore. I think it is because the first argument of run_bh_tsne now expects an input_file and not a numpy array anymore. The function bh_tsne now makes a numpy array using this input_file. 

Is this intended behaviour? In my opinion it would be better to provide both ways: start bh_tsne with input file and with a numpy array.

The error message:

```
File "/home/hans/wart-detection/bhtsne.py", line 206, in run_bh_tsne
    init_bh_tsne(input_file, tmp_dir_path, no_dims=no_dims, perplexity=perplexity, theta=theta, randseed=randseed,verbose=verbose, initial_dims=initial_dims, use_pca=use_pca, max_iter=max_iter)
  File "/home/hans/wart-detection/bhtsne.py", line 101, in init_bh_tsne
    for l in input_file), start=1):
  File "/home/hans/wart-detection/bhtsne.py", line 101, in <genexpr>
    for l in input_file), start=1):
AttributeError: 'numpy.ndarray' object has no attribute 'rstrip'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <function _remove at 0x7fb39c57a6e0> ignored
```

**Comment by lvdmaaten** [comment]
Agreed. 

@make Could you update #29 accordingly?

**Comment by lvdmaaten** [comment]
Does https://github.com/lvdmaaten/bhtsne/pull/32 fix this for you?

**Comment by HansPinckaers** [comment]
No, it doesn't crash anymore, but it doesn't seem to run (no bh_tsne process is spawned), and the script hangs. This could be because of the os.fork the script is now using. I never had success using that on Mac OS, could be my dev environment config though.

**Comment by lvdmaaten** [comment]
Yuck! Let me try and look into that later today...
