### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by xuanzhaopeng** [lvdmaaten/bhtsne#33]
0x0000000000403662 in TSNE::computeGaussianPerplexity (this=0x612010, X=0x7ffff6fab010, N=10000, D=30, _row_P=0x7fffffffe3d0, _col_P=0x7fffffffe3d8,
    _val_P=0x7fffffffe3e0, perplexity=50, K=150) at tsne.cpp:470
470                     cur_P[m] = exp(-beta * distances[m + 1] * distances[m + 1]);

The reason is sizeof(distance) = 24, but K = 150,  how it works??

**Comment by lvdmaaten** [comment]
Can you please provide more details? What is the size of your input data,
how do you execute the code, what are the input parameters, etc.?

I cannot resolve potential issues if I cannot reproduce them.

**Comment by GoXian** [comment]
> 0x0000000000403662 in TSNE::computeGaussianPerplexity (this=0x612010, X=0x7ffff6fab010, N=10000, D=30, _row_P=0x7fffffffe3d0, _col_P=0x7fffffffe3d8, _val_P=0x7fffffffe3e0, perplexity=50, K=150) at tsne.cpp:470 470 cur_P[m] = exp(-beta * distances[m + 1] * distances[m + 1]);
> 
> The reason is sizeof(distance) = 24, but K = 150, how it works??

请问最后你是如何解决的
