### ISSUE TITLE
Support for Ubuntu 14.04 LTS?

### ISSUE THREAD

**Issue by djebm2** [lvdmaaten/bhtsne#38]
Does this implementation supports Ubuntu 14.04 LTS ? Would that be possible to add a clean documentation for this ?

**Comment by lvdmaaten** [comment]
I don't have an Ubuntu installation so I cannot check this. Having said this, the code is pretty much vanilla C/C++ code with very few dependencies. Presuming you can run gcc, why wouldn't it compile on Ubuntu?
