### ISSUE TITLE
Out-of-sample

### ISSUE THREAD

**Issue by skn123** [lvdmaaten/bhtsne#4]
Is there an OOS extension for t-SNE?

**Comment by lvdmaaten** [comment]
No. t-SNE is a non-parametric technique, which means it does not learn an explicit mapping from the input space to the output space. As a result, there is no out-of-sample extension for t-SNE (although you could come up with nearest-neighbor hacks to do it).

A more principled way to do OOS would be to train a deep net to minimize the t-SNE loss (or train it as a regressor between both spaces), but that is outside the scope of this project. See for http://lvdmaaten.github.io/publications/papers/AISTATS_2009.pdf details.
