### ISSUE TITLE
There is no module called bhtsne.run_bh_tsne ???

### ISSUE THREAD

**Issue by wa1618i** [lvdmaaten/bhtsne#59]
I can install bhtsne using my vcvars32.bat.

But...
I can't run the example in the front page:
data = np.loadtxt("mnist2500_X.txt", skiprows=1)
embedding_array = bhtsne.run_bh_tsne(data, initial_dims=data.shape[1])
However, i can run using bhtsne.tsne(data).

The question is...
Is bhtsne.tsne the same as bhtsne.run_bh_tsne above? Also, setting verbose=True under bhtsne.py doesn't produce verbose text as usual in my SPYDER (python 2.7 anaconda) console.

**Comment by ericjster** [comment]
You should examine the python code, bhtsne.py, it is just a small wrapper.
Note that the executable (bh_tsne.exe) should be in the same directory as bhtsne.py.
There exists a function bg_tsne(workdir) but you probably do want to use run_bh_tsne so you can set parameters. You can also use from the command line, e.g. "python bhtsne.py -i mydata.tsv -o mytsne.tsv --use_pca".
BTW I just used it on a a data set with 154K rows x 22 columns. Mapping to 2 dimensions took 1 hour, and to 3 dimensions took 2 hours. The sklearn implementation failed immediately.
