### ISSUE TITLE
Help ME! thanks!

### ISSUE THREAD

**Issue by FlyDogFan** [lvdmaaten/bhtsne#60]
HELP!!!  troubles in HLLE.m ，when i put  minst dataset in hlle ,it come out a error  in line 118 "[mappedX, eigenvals] = eigs(G, no_dims + 1, tol, options);" .
"""
Error in eigs (line 93)
[A,Amatrix,isrealprob,issymA,n,B,classAB,k,eigs_sigma,whch, ...
Error in hlle (line 118)
        [mappedX, eigenvals] = eigs(G , no_dims + 1, tol, options);
Error in test_hlle_minst (line 8)
[mappedX] = hlle(train_X, 2, 12); 
"""
i would  be very appreciate if you could  help me overcome these errors! 
thank U!

**Comment by lvdmaaten** [comment]
Question is unrelated to this repo.
