### ISSUE TITLE
Usage of random generator(s) in the source

### ISSUE THREAD

**Issue by NikTuzov** [lvdmaaten/bhtsne#61]
Hello Laurens:

I am trying to have full control of results in the sense of getting exactly the same output for a given random seed. Could you please confirm that I got it right: there are only two places where a random generator is used:

1) When the user wants to initialize Y via Normal distribution.
2) In vptree.h there is a single line ("Create an arbitrary point...") where a random generator is used. 

Thanks,
Nik Tuzov, PhD

**Comment by lvdmaaten** [comment]
Yes, I think those are the only two places where the code is non-deterministic.

**Comment by NikTuzov** [comment]
Thank you.
