### ISSUE TITLE
Why is the exact algorithm 10 times faster?

### ISSUE THREAD

**Issue by k8280627** [lvdmaaten/bhtsne#68]
Hi, I was wondering about the speed of exact tsne and Barnes-Hut tsne in C++ code.

In my case, the speed of exact tsne is almost 10 times faster than BH tsne, which does not make much sense theoretically. Have anyone encountered the similar results? 

If exact tsne is faster in the C++ version, could anyone explain a bit about why this is the case? Really appreciate it!!

**Comment by lvdmaaten** [comment]
What is the size of the dataset you feed the algorithm? And what value of theta do you use when you run Barnes-Hut t-SNE?

**Comment by k8280627** [comment]
I fed N = 2500 and 7000. I use theta = 0 for exact, and tried theta = 1e-3, 1e-7 for Barnes-Hut tsne.

**Comment by lvdmaaten** [comment]
Try larger values for theta. Theta determines how many branches of the quadtree are being pruned; larger values of theta imply more pruning, which, in turn, implies faster speed and slightly less accurate results.

In most of my experiments, I found theta = 0.5 to be a good trade-off between speed and quality.

**Comment by k8280627** [comment]
Thanks for the suggestion! I just tried out and found out that if I use 2500 samples with dimension=102, for the exact algorithm (theta = 0), it took 9.44 sec to run 50 iterations. For BH tsne, I tried theta = 0.5, 1 and it took ~65 sec and ~70 sec for 50 iterations. Is this unusual?
If it is, there might be something wrong with my experiment....

**Comment by lvdmaaten** [comment]
Yeah, that is quite unexpected. Does your data have duplicates (or near-duplicates) by any chance?

**Comment by k8280627** [comment]
I am not quite sure about my data. 

But I tried MNIST, when using N=2500, theta=0 takes ~9 sec per 50 iters, and theta=0.5 takes 68 sec per 50 iters. 

When N = 10000, theta=0 takes 150 sec per 50 iters, and theta=0.5 takes 281 sec per 50 iters. 

I could not try N = 20000+ right now since my PC does not have enough computing power.

I was suspecting if it's because I was using relatively small datasets, so the speed of BH t-sne is not working faster (as expected) than the exact t-sne? If I may ask, have you dealt with smaller datasets before? 

Thank you so very much for answering all my questions. It's very helpful to me!

**Comment by k8280627** [comment]
I am not quite sure whether my data would have near duplicates. But I tried MNIST and has got similar results.

When using N=2500, theta=0 takes ~9 sec per 50 iters, and theta=0.5 takes 68 sec per 50 iters. 

When N = 10000, theta=0 takes 150 sec per 50 iters, and theta=0.5 takes 281 sec per 50 iters. 

I could not try N = 20000+ right now since my PC does not have enough computing power.

I was suspecting if there's a slight chance that the computing power of PC would affect the result?

Thank you so very much for answering all my questions. It's very helpful to me!

**Comment by lvdmaaten** [comment]
The exact numbers may vary per CPU, but I see no reason why they would vary as much as you describe in your post. Are you sure you compiled the `bhtsne` binary in optimized mode (`-O2` / `-O3`) rather than in debug mode?

Running the MNIST example with N=2500 from the `README` using the Python wrapper, I see the following timings on my Macbook Pro (3.5 GHz Intel Core i7):

```
>>> import time
>>> import numpy as np
>>> import bhtsne
>>> data = np.loadtxt("mnist2500_X.txt", skiprows=1)
>>> start_time = time.time(); embedding_array = bhtsne.run_bh_tsne(data, initial_dims=data.shape[1], theta=0.5); end_time = time.time();
>>> print(end_time - start_time)
24.6498529911
>>> start_time = time.time(); embedding_array = bhtsne.run_bh_tsne(data, initial_dims=data.shape[1], theta=0.0); end_time = time.time();
>>> print(end_time - start_time)
68.8492469788
```
