### ISSUE TITLE
Can I use a pairwise similarity matrix as input into bhtsne?

### ISSUE THREAD

**Issue by directorscut82** [lvdmaaten/bhtsne#7]
hello,
is there a similar way to tsne_p.m for performing fast_tsne (i.e provide the pairwise similarity matrix)?

If not, 
is it appropriate if i add an option to computeSquaredEuclideanDistance for computing a gaussian kernel with custom DD (as in exp(-beta * DD[nN + m])) and an equivelent vptree distance, 
or euclidean DDistances are the only way for the fast version  to work correctly?

**Comment by lvdmaaten** [comment]
I think using a pairwise distance matrix as input does not make much sense: Barnes-Hut algorithms are intended to operate on large datasets for which you cannot keep such distance matrices in memory. If your distance matrix is small enough to keep it in memory, one may as well use a standard implementation of t-SNE.

Allowing the user to use any distance function would be a nice feature to have, and should be relatively straightforward to implement. My only concern here is that the distance function should implement a metric, or the vantage-point tree algorithm may not work correctly. As long as we make this clear in the documentation, I don't think it is necessary to explicitly check whether the metric assumptions are violated (as it would be expensive to do so). Feel free to send a PR implementing this.

**Comment by directorscut82** [comment]
In (hyper)spectral imaging we like our similarities to be insensitive to illumination, so an angle-based distance metric is much more preferred to a simple Euclidean.

+Thank you for the quick responce..

**Comment by lvdmaaten** [comment]
Angle-based metrics are generally not metric (they violate the identity of indiscernibles condition and the triangle inequality).

**Comment by directorscut82** [comment]
You are absolutely correct, 
but for a physical quantity as a spectrum we can limit the possible angle range to 0-pi/2, violating only the triangle inequality. 

The first three (non-negativity, identity of indiscernibles & symmetry) establish a positive-definite function (alas not a metric but i think its ok for kernel contraptions:).

**Comment by directorscut82** [comment]
Just for completeness,
after reviewing the link/tutorial you provided (within the codebase) and especially the original paper ("Data Structures and Algorithms for Nearest Neighbor Search in General Metric Spaces"), i was (very) lucky to notice that the vp-tree author have already tested performance on two non-Euclidian cases where the first is a pseudometric angle based distance with a very positive report (yay).

**Comment by lvdmaaten** [comment]
It should be straightforward to do as long as your distance is an actual metric, since the vantage-point tree is already takes a `distance` template. So you can replace this bit of code by your own distance metric: https://github.com/lvdmaaten/bhtsne/blob/master/vptree.h#L90-L104

Having said that, cosine distance violates the triangle inequality and identity of the indiscernibles, so you cannot use it with vantage-point trees (well you can, but there is no guarantee you'll get correct results).

**Comment by jlorince** [comment]
Awesome - was hoping there was something simple to plug-and-play, as it were (my c++ is horribly weak). Perhaps the [angular distance](https://en.wikipedia.org/wiki/Cosine_similarity#Angular_distance_and_similarity) would be good to use here, as it's a proper distance metric and should behave similarly to cosine distance (I think...)

**Comment by jlorince** [comment]
Are you certain that's the only thing that would need changing? As a hacked-together experiment, I tried modifying the euclidean distance function to:

    double euclidean_distance(const DataPoint &t1, const DataPoint &t2) {
        double dp = 0.0;
        double denom_a = 0.0;
        double denom_b = 0.0;
        double* x1 = t1._x;
        double* x2 = t2._x;
        for(int d = 0; d < t1._D; d++) {
            dp += x1[d] * x2[d];
            denom_a += x1[d] * x2[d];
            denom_b += x1[d] * x2[d];
        }
        return dp / (sqrt(denom_a) * sqrt(denom_b));
    }

It compiles fine, but when I try running it I get `AssertionError: ERROR: Call to bh_tsne exited with a non-zero return code exit status, please refer to the bh_tsne output for further details`. But there's not output for me to refer to...

**Comment by directorscut82** [comment]
@jlorince  Maybe this can clear some things:: [angular distance vs. metric](http://math.stackexchange.com/questions/102924/cosine-similarity-distance-and-triangle-equation?rq=1)

**Comment by stonexjr** [comment]
@jlorince Plus, your `euclidean_distance` implementation looks buggy. 
why it was `denom_a += x1[d] * x2[d]` instead of `denom_a += x1[d] * x1[d]`?
Your `denom_a` and `denom_b` would have the same value after the for loop, and the function would always returns `1` disregard of the input `t1` and `t2`
