### ISSUE TITLE
Dimension problem

### ISSUE THREAD

**Issue by dcharua** [lvdmaaten/bhtsne#70]
Hello,  
Im trying to use the code for a image dataset that is in a h5 file, i changed the load data function in the python wrapper for this

```
def load_data(input_file):
    with h5py.File('data4.h5', 'r') as hf:
    	data = hf['data1'][:]
    return data

```
Where data1 is the name of the dataset inside the h5 file
But i get the following error
```
Traceback (most recent call last)
  File "bhtsne.py", line 246, in <module>
    exit(main(argv))
  File "bhtsne.py", line 237, in main
    verbose=argp.verbose, initial_dims=argp.initial_dims, use_pca=argp.use_pca, max_iter=argp.max_iter):
  File "bhtsne.py", line 208, in run_bh_tsne
    init_bh_tsne(data, tmp_dir_path, no_dims=no_dims, perplexity=perplexity, theta=theta, randseed=randseed,verbose=verbose, initial_dims=initial_dims, use_pca=use_pca, max_iter=max_iter)
  File "bhtsne.py", line 112, in init_bh_tsne
    cov_x = np.dot(np.transpose(samples), samples)
ValueError: shapes (32,32,3,2462) and (2462,3,32,32) not aligned: 2462 (dim 3) != 32 (dim 2)
Traceback (most recent call last):
  File "bhtsne.py", line 246, in <module>
    exit(main(argv))
  File "bhtsne.py", line 237, in main
    verbose=argp.verbose, initial_dims=argp.initial_dims, use_pca=argp.use_pca, max_iter=argp.max_iter):
  File "bhtsne.py", line 218, in run_bh_tsne
    for result in bh_tsne(tmp_dir_path, verbose):
  File "bhtsne.py", line 163, in bh_tsne
    with open(path_join(workdir, 'result.dat'), 'rb') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpx2rn_uow/result.dat'
```

How can I read my dataset correctly?
If its not possible I still have the data in a folder structure where each folder represents a category, sorry for my lack of knowledge but can I pass it and should pass it to a csv file?

Thank you very much

**Comment by lvdmaaten** [comment]
I have never used `h5py`, does it return a NumPy array?

The most likely explanations would be your process not having permissions to create a temporary directory [here](https://github.com/lvdmaaten/bhtsne/blob/master/bhtsne.py#L196) or a temporary file [here](https://github.com/lvdmaaten/bhtsne/blob/master/bhtsne.py#L130). This will be difficult to debug for me without a repro.

**Comment by dcharua** [comment]
Thank you for the quick response, It does returns a numpy array if I run data.shape I get  (2462, 3, 32, 32).
so the error is here:

> File "bhtsne.py", line 112, in init_bh_tsne
>     cov_x = np.dot(np.transpose(samples), samples)
> ValueError: shapes (32,32,3,2462) and (2462,3,32,32) not aligned: 2462 (dim 3) != 32 (dim 2)

Something about the dimensions doesn't add up when doing the .dot between the transpose and the original matrix.

How can I import my dataset? I can try to read directly from the folders into a np.array but  in what format does it needs to be?

Thank you very much

**Comment by lvdmaaten** [comment]
Your dataset should be a matrix of size NxD, where N is the number of examples and D is the number of dimensions. Please reshape your data matrix to size 2462x(3x32x32) before feeding it to t-SNE.
