### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by FlorianUekermann** [lvdmaaten/bhtsne#78]
Both `tsne.h` and `tsne_main.cpp` seem to be almost entirely C code. Would you be opposed to a pull request making them C compatible? This would make your code usable as both C and C++ library, allowing for easy implementation of language bindings without intermediate files.

I am interested in this for the C library bindings and for contributing Go bindings.

**Comment by lvdmaaten** [comment]
Yeah, definitely! The current way of data serialization via files is obviously incredibly clunky.

This shouldn't require many code changes: adding a single C function that calls `TSNE::run` and is wrapped in an `extern "C"` block should suffice?

**Comment by FlorianUekermann** [comment]
Yes, pretty much. I thought since its pretty much entirely C anyway, the cleanest option would be just turn the two mentioned files plain C. The class seems to be abused as namespace. Anyway, I'll send a PR, then you can have a look.

**Comment by FlorianUekermann** [comment]
Thanks for merging.
