### ISSUE TITLE
No PCA dimensionality reduction in the Python wrapper before calling C++ BH library

### ISSUE THREAD

**Issue by philipperemy** [lvdmaaten/bhtsne#8]
I'm working to integrate it to have an homogenous framework. @lvdmaaten Do you think it could be relevant? Thanks!

**Comment by lvdmaaten** [comment]
@philipperemy Yeah, I think it would make sense to add the PCA preprocessing. It typically improves the performance of the method (both in terms of speed and in terms of map quality), and it would make things more consistent with the Matlab wrapper. I'm not much of a Python user myself, so I just never got around to adding it.

**Comment by lvdmaaten** [comment]
Closed by https://github.com/lvdmaaten/bhtsne/pull/9
